
<?php 

	$id = $this->getLinkCreate($prodId);

	$_product = $block->getProductById($id);

	echo $_product->getEntityId();
	echo '<br />';
	echo $_product->getName();

	
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

	$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');

	$addToCartUrl =  $listBlock->getAddToCartUrl($_product);
?>
 <form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
    <?php echo $block->getBlockHtml('formkey')?>
       <button type="submit"
               title="Add to Cart"
               class="action tocart primary">
               <span>Add to Cart</span>
        </button>
 </form>

